{%- if pillar.cinder.controller is defined %}
[logstreamer_cinder_scheduler]
type = "LogstreamerInput"
log_directory = "/var/log/cinder"
file_match = 'cinder-scheduler\.log\.?(?P<Index>\d+)?(.gz)?'
priority = ["^Index"]
decoder = "openstack"
oldest_duration: "168h"

[logstreamer_cinder_manage]
type = "LogstreamerInput"
log_directory = "/var/log/cinder"
file_match = 'cinder-manage\.log\.?(?P<Index>\d+)?(.gz)?'
priority = ["^Index"]
decoder = "openstack"
oldest_duration: "168h"
{%- endif %}

{%- if pillar.cinder.volume is defined %}
[logstreamer_cinder_volume]
type = "LogstreamerInput"
log_directory = "/var/log/cinder"
file_match = 'cinder-volume\.log\.?(?P<Index>\d+)?(.gz)?'
priority = ["^Index"]
decoder = "openstack"
oldest_duration: "168h"
{%- endif %}

[openstack]
type = "SandboxDecoder"
filename = "lua_modules/decoders/openstack.lua"
module_directory = "/usr/share/heka/lua_modules;/usr/share/heka/lua_modules/common"
