---
driver:
  name: docker
  hostname: cinder.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: cinder
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - cinder
  pillars:
    top.sls:
      base:
        "*":
          - cinder

verifier:
  name: inspec
  sudo: true

platforms:
  - name: ubuntu-trusty
    driver_config:
      image: trevorj/salty-whales:trusty
      platform: ubuntu

  - name: ubuntu-xenial
    driver_config:
      image: trevorj/salty-whales:xenial
      platform: ubuntu

suites:

  - name: <%=ENV['SUITE'] || 'ceph_single'%>
    provisioner:
      pillars-from-files:
        cinder.sls: tests/pillar/<%=ENV['SUITE'] || 'ceph_single'%>.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
